### PR TITLE
work in progress: deterministic, deduped packing

### PR DESCRIPTION
**Pull request by dominictarr**
@heavyk hey i started on this. it separates the files from the trees.
Just have to figure out the prelude. Instead of pre-minifying the prelude it just toStrings a function.
I think this is better because then we don't need to use fs and so everything the bundle needs is in the bundle.

### CODE REVIEW

**Comment by heavyk** [comment]
yeah, I like where this is going, a lot. much more efficient.

it's good not to read the file, then re-read the file again in nodepack. that's an advantage along with needing one less dependency. your hash implementation is a lot better too.

I'm excited to play around with this when I wake up tomorrow.

also, I'm not sure I understood what you meant, in the other PR, about a file having different deps. I thought that in the end, that's the whole point of having one file (module) with one module.exports. an npm "module" is composed of a bunch of modules - each one being a file. so, unless that file is sharing some sort of state with another module/file (which could possibly happen, perhaps - I honestly don't even know how to do that.. maybe modify data in module exports), then I would think that module is "pure" and shouldn't matter. can you explain better?

oh, it just occured to me, that if we were to see, `const pull = require('pull-stream')` then that file, or "module" can be considered pure.

**Comment by heavyk** [comment]
hmmm, perhaps you mean an example such as this one: https://iojs.org/api/modules.html#modules_module_exports where exports is an instantiated class?

well, even then, deduping files would still work... right? I think. gonna keep thinking on this.

in personal experience, I've always deduped files and have not had a problem yet... I dunno maybe I was lucky :)

**Comment by dominictarr** [comment]
no what i mean is about how you can have identical files, but in different places.
normally you think of files as being their name, and so if you have foo/index.js and bar/index.js those are two different files. But if you take the perspective of secure decentralized systems, which we are when we start hashing things, then we understand the names are just pointers. So the two files can be identical (same hashes) but different names (copied into multiple places). maybe each file loads another module relative to itself called "util" so we have foo/util.js and bar/util.js. maybe index.js is just `module.exports = require('./util')` for both indexes. that is completely fine, in node. But, the util files might not be the same!
This means that although both index.js are identical, they don't do the same thing, because they have different dependencies.

If you have multilpe versions of a package in a bundle, and those packages have multiple files, it's quite possible not all the files change between versions, but the files around them do. 

So, this is why we can dedupe the content, but not the dep tree. (although, npm will dedupe that as best as it can, especially in npm@3)

**Comment by heavyk** [comment]
ohh, ok I see what you're saying about both index files having `require('./util')` and the util files being different... that makes sense.

though I still think it would work fine because `resolve()` will resolve them as absolute paths - which will then be different. so, even if both `foo` and `bar` have the same content, they will still be requiring different files (because resolve has resolved them to be different files).

therefore, in the prelude all we need to do is to ensure that even though the content of the file is the same, the require function will be coming from a different __dirname. this can easily be verified with a test.

 - foo/index.js -> `module.exports = require('./util')`
  - with `__filename` set to the abs path [...]/foo/index.js
  - with `__dirname` set to the abs path [...]/foo
 - bar/index.js -> `module.exports = require('./util')`
  - with `__filename` set to the abs path [...]/bar/index.js
  - with `__dirname` set to the abs path [...]/bar

so therefore I conclude that even if the content (hash) of the file is the same, the only thing that needs looking after, is that it's done from the correct "perspective" of that require... right?

so, before I say any more, I'm going to play around with this code a little bit. last night I couldn't exactly wrap my head around it

cheers

**Comment by heavyk** [comment]
thinking about this a bit more, I think we actually resolve the problem that npm has, because we pre-resolve (so it's not doing a relative require from an incorrect location).
therefore I think our system will actually be more efficient and non-deduped because we can separate the context and content of the require.

:D glad we thought about this. I see a brighter future already!

**Comment by dominictarr** [comment]
okay I got the new pack working. this made noderifying noderify 400k smaller!

**Comment by dominictarr** [comment]
by the way, this breaks the option you made for a custom prelude? what did you use that for?

**Comment by dominictarr** [comment]
merged into 1.0.0

**Comment by heavyk** [comment]
delete it. it was to define a custom prelude, however now it would just require the replacement of the function in pack.js (it looks).

when I get back into our servers again I'll make a PR. I used the function previously to draw a map of what requires were used, and when -- so it's useful -- for limited use cases :)

**Pull request merged**
