### PR TITLE
Superior bundler

### PR DESCRIPTION
**Pull request by heavyk**
so, I kept working on it and I'm pretty satisfied with the result now. here are the improvements.

 * no more filtered modules (relative path native modules (eg. sodium) all work fine now)
 * everything is bundled unless you filter out some modules (noderify -f leveldown bin.js will filter leveldown out of the bundle)
 * did some hackery to fix up modules which use `bindings` to require their native extension. these work too.
 * instead of silently skipping dependencies, it will alert you now if something's missing (potentially npmd integration could be used to install any missing deps)

where I was thinking I'd like to take this:
 - I want it be create an output directory with the bundle in it, a build/Release/*.node files + any additional assets.
 - I'll have it optionally tar and compress that directory -- now just one single tar file with bundle, native modules prebuilt and assets - very flat and fast tiny tiny easily deployable "servers"

sidenote: I have no use for this - but it would be *very* easy to precompile the native modules for various platforms before making the tar. would be really good for distributing stuff.

### CODE REVIEW

**Comment by dominictarr** [comment]
This look really good!!!

Just trying to figure out how you are resolving .node files.

This regular expression needs to allow uppercase, numbers, and underscore:
https://github.com/dominictarr/noderify/pull/3/files#diff-168726dbe96b3ce427e7fedce31bb0bcR61
maybe explicitly check ' or " too.

Hmm, so it looks like you are taking the .node files and then changing their require statements to point to the path relative to the bundle root?

hmm... maybe instead of a regular expression could change the prelude or add another file which reexported the correct path?

I really like the idea moving the .node files locally and making a min bundle.
What about how to handle mac/linux/windows?

**Comment by dominictarr** [comment]
I will merge this, but i'd rather use a fork of browser-pack instead of updating it's code.

**Comment by heavyk** [comment]
what I do is I convert the .node location to its location relative to the basedir of the file you're parsing, eg:
```
chloride/build/Release/sodium -> node_modules/secret-stack/node_modules/secret-handshake/node_modules/chloride/build/Release/sodium.node
../build/Release/sodium -> node_modules/secret-stack/node_modules/secret-handshake/node_modules/chloride/build/Release/sodium.node
../../build/Release/sodium -> node_modules/secret-stack/node_modules/secret-handshake/node_modules/chloride/build/Release/sodium.node
./build/Release/leveldown.node -> node_modules/leveldown/build/Release/leveldown.node
```

that is done where it says secret magic sauce. so, in that same location, the node file could easily be moved to `build/darwin/2.5.0/leveldown.node` for example...now you have cross platform builds :)

**Comment by heavyk** [comment]
good points on the regex. updated. btw what's the problem with patching browser-pack like that?
(as if all the rest of the hackery was perfectly legal, lol)

I did it that way, cause you patched an old version of browser-pack and I also had interest in providing my own prelude anyway to get stats and further improve the bundle optimizatoin. for example, I wanted to use hashes instead of paths for requires, and also figure out how to remove duplication on very reused functions, and just use require to get those, etc.

**Comment by heavyk** [comment]
let me explain a bit better about what I mean by function hashes. I had this idea that we could take reduce all pure functions (no scope dependence or closures) and start with those, hash the ast of those functions with the values all normalized, so `function (a) {return a + 1} is the same as `function lala (b) {return b + 1}` etc.

this idea comes from the need to have source code not tampered with. so, if you hash a pure function let's say a hashing function `sha256` it's name will instead be `xxxxxxxxxxxxxxxxxxxxxxxxxxxxx` and you know your function is indeed doing what you want it to do, you can `toString()` it to get its source (because it's pure) parse it, then verify the function you are using does in fact hash back to the same hash. this is the only way I've come up with to ensure js functions really do what they do.

the drawback to this technique is that functions have to be pure for this to work, right? then I had an epiphany and realized that this same idea could be applied to "modules" -- so since then, I've wanted to do this idea, but just have not until now... last night was kinda like my first step in that direction.

so my goal will be soon to parse all the ssb source and do requires based on hashes. what do you think of that idea?

**Comment by dominictarr** [comment]
okay well one very good argument against patching a file like that is that now it's not gonna work with noderify ;) but it would if we just used a fork. Basically it's just a very weird way to do that, and could cause weird problems...

like, what if one part of the program requires browser-pack, then this part update it's code. on a fresh install it would fail the first time, but succeed the second. so your tests always fail on travis, but they seem to work locally.

The other things we are doing, like remapping the native requires is different. you arn't altering source files on disk, there *could* be some problems with the regexps, since it doesn't actually parse the code, it could replace requires that are actually inside a string, for example.

I think it's acceptable to use the regexp, but it would still be better to find a cleaner way.

**Comment by dominictarr** [comment]
ah, @heavyk i'll update nodepack to be based on the latest brower-pack.

I'm glad you are thinking about the hashed modules. I was thinking about this too.
We want ssb to be a platform for secure programming, so everything is hashed and signed.
This would also make comparing bundles easy!

**Comment by heavyk** [comment]
I see what you're saying about the module potentially being used by another module and it not working as expected. that's a *very* valid point. so instead, what if I were to -- instead of writing the file to disk and requiring it, like I'm doing now -- I ran it in `vm.runInNewContext`? no one gets hurt that way.

come to think of it I really like that idea. I do these sorts of patches all the time, so potentially, it'd be good to create a toolset to do that better. actually, that's one of the reasons why I took interest in this project: it makes patching easier :D hehe

so.. I don't really want to discuss too much about file patching. it's silly. there are way more cool things to do anyway. I'd much rather create a better alternative...

update nodepack and I'll update the PR, for sure

---

ok, so I wanna get back to the hashing stuff I was talking about. first, I'm gonna write the runInNewContext code (whether we use it or not) and get back to you on the hashing stuff. I have a ton of ideas.

it's always bothered me that js code is in plain text and sent over the wire. no real easy way to unsure the crypto lib your using isn't compromised... so, instead I think that if the code's signature is a hash of it structure, detecting subtle changes would be easy - so then code will soon become patches of patches... sorta like how human genome is mostly composed of viral dna :) anyway..

**Comment by dominictarr** [comment]
okay, nodepack is now up to date with the latest browser-pack, although I have skipped the source map tests.

**Comment by heavyk** [comment]
updated. merge away, or do you want a squash?

**Comment by heavyk** [comment]
I'll get the source maps later. they're not important now.. getting a stack trace with source maps in node is a bit hacky iirc

**Comment by dominictarr** [comment]
merged into 0.1.0

I also had to update nodepack because i had put the __dirname and __filename the wrong way around.
This can now also bundle itself (907k javascript!) and it seems to work, although, race conditions module-deps means we get a different order each time... if the same input produced the same output, we could test it by bundling `noderify` with `noderify` (to give `noderify'`) and using noderify' to bundle `noderify` again, (to give `noderify''`) and then checking that `noderify' === noderify''`

**Comment by heavyk** [comment]
nice :) there's probably no easy way to order the reads to be able to test that, so... whatever

I was playing with your idea, and I discovered a bug:
```
$ node noderify2.js index.js > noderify3.js
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOTDIR: not a directory, open '/Users/kenny/Projects/github.com/heavyk/noderify/node_modules/nodepack/index.js/_prelude.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object./Users/kenny/Projects/github.com/heavyk/noderify/node_modules/nodepack/index.js.JSONStream (/Users/kenny/Projects/github.com/heavyk/noderify/noderify2.js:25087:25)
    at s (/Users/kenny/Projects/github.com/heavyk/noderify/noderify2.js:1:325)
    at /Users/kenny/Projects/github.com/heavyk/noderify/noderify2.js:1:376
    at Object./Users/kenny/Projects/github.com/heavyk/noderify/index.js../package.json (/Users/kenny/Projects/github.com/heavyk/noderify/noderify2.js:27622:16)
    at s (/Users/kenny/Projects/github.com/heavyk/noderify/noderify2.js:1:325)
    at /Users/kenny/Projects/github.com/heavyk/noderify/package.json.module.exports.name (/Users/kenny/Projects/github.com/heavyk/noderify/noderify2.js:1:511)
    at Object.<anonymous> (/Users/kenny/Projects/github.com/heavyk/noderify/noderify2.js:1:529)
```

**Comment by heavyk** [comment]
I'll look when I wake up, but this seems to be a problem -- somewhere .. I was excited about making `noderify''` but it's not working for me:

```
➜  noderify git:(master) noderify index.js > noderify3.js
➜  noderify git:(master) ./noderify3.js
./noderify3.js: line 1: syntax error near unexpected token `('
./noderify3.js: line 1: `(function(t,n,r){function s(e,r,o){if(!n[e]){if(!t[e]){var u=typeof require=="function"&&require;if(!r&&u)return u(e,!0);if(i)return i(e,!0);var a=new Error("Cannot find module '"+e+"'");throw a.code="MODULE_NOT_FOUND",a}var f=t[e][2],l=f+"/"+t[e][3],c=n[e]={exports:{},parent:o};t[e][0].call(c.exports,function(n){var r=t[e][1][n];return s(r?r:n,null,c)},c,c.exports,f,l)}return n[e].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"/Users/kenny/Projects/github.com/heavyk/noderify/package.json":[function(require,module,exports,__dirname,__filename){'
```

P.S. I think the error in the previous message might have been from still having nodepack@6.0.1 (instead of 6.0.2) ... the above error though still happens even though scuttlebot can be noderified fine.
P.P.S. noderified -- lol :)

**Pull request merged**
