### PR TITLE
pack: fix __dirname

### PR DESCRIPTION
**Pull request by juliangruber**
__dirname would just be the filename without the dir, the opposite of what you'd want

### CODE REVIEW

**Comment by dominictarr** [comment]
I don't quite understand what the difference is. do you have an example where this causes a bug?
it should probably use `path.dirname(filename)` instead

**Comment by juliangruber** [comment]
it fails for two reasons:

```bash
 ∴  ~ : node
> // __dirname won't be an absolute path
> var file = 'index.js'
undefined
> file.substring(file.lastIndexOf('/'))
'index.js'
> // dirname won't contain the dir
> file = '/foo/bar/index.js'
'/foo/bar/index.js'
> file.substring(file.lastIndexOf('/'))
'/index.js'
>
```

you're right that `path.dirname()` is better, I'll update

**Comment by 0x00A** [comment]
@dominictarr this seems to work, any other reservations?

**Comment by dominictarr** [comment]
Okay, I have merged this into 1.1.8...

I just realized that this stopped loading node bindings correctly at https://github.com/dominictarr/noderify/commit/0fca4455a1633b142ebbd5d4690b491a370ff0a6

I think, but there wasn't test coverage for that, so didn't realize until now.

I'd rather not require `path` in the prelude, because then the file isn't truly self contained...
Later, I'd like to use this for sandboxing a process, and to have path used means you'd have to audit path, and wouldn't know what changes between node versions. This doesn't really matter right now though, so we can fix it later.

I think the problem here, is that I thought `path.relative` would return paths of the form `./path...` which would have made the substring thing work. Again, we can fix that later.

can I ask, what are you using this for?

**Comment by 0x00A** [comment]
bundle as much as possible to reduce electron startup time.

**Comment by juliangruber** [comment]
> I'd rather not require path in the prelude, because then the file isn't truly self contained...

I thought about that as well, and I agree it would be nice to refactor that later on.

> I just realized that this stopped loading node bindings correctly at 0fca445

It did work with the native modules in the app we were testing though.

> can I ask, what are you using this for?

For example the module jade took quite a long time to require. With electron it's nice to get the ui to be responsive right away, and node startup time per se isn't the best either, so this is especially valuable for electron apps.

**Comment by dominictarr** [comment]
Oh, oops. It was actually a thing I was doing wrong over here: https://github.com/dominictarr/chloride/commit/19457e05476eb3019c5de3f9d41ca395d718a634

we should add some test coverage binary addons, though.

**Pull request merged**
